# -*- coding: utf-8 -*-
"""V2.1.1 · 补充 Person 规格 · 批次D：日本近代军事人物 / 裕仁（中性史实描述）"""

from __future__ import annotations

from typing import Any

PERSON_SPECS: dict[str, dict[str, Any]] = {
    "curated-person-ishihara-kanji": {
        "id": "curated-person-ishihara-kanji",
        "name_raw": "石原莞尔",
        "canonical_name_zh_cn": "石原莞尔",
        "traditional_name": "石原莞爾",
        "birth_year": 1889,
        "death_year": 1949,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["石原莞爾", "石原莞儿"],
        "intro_zh_cn": "日本陆军军官，九一八事变的主要策划者之一。",
        "source_reference": "《石原莞尔与九一八事变》；步步为营丛书·满洲事变史料",
    },
    "curated-person-itagaki-seishiro": {
        "id": "curated-person-itagaki-seishiro",
        "name_raw": "板垣征四郎",
        "canonical_name_zh_cn": "板垣征四郎",
        "traditional_name": "板垣征四郎",
        "birth_year": 1885,
        "death_year": 1948,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["板桓征四郎"],
        "intro_zh_cn": "日本陆军军官，九一八事变时关东军高级参谋之一。",
        "source_reference": "东京审判个人案卷（IMFTE 判决书）",
    },
    "curated-person-matsui-iwane": {
        "id": "curated-person-matsui-iwane",
        "name_raw": "松井石根",
        "canonical_name_zh_cn": "松井石根",
        "traditional_name": "松井石根",
        "birth_year": 1878,
        "death_year": 1948,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["松井石根"],
        "intro_zh_cn": "日本陆军大将，上海派遣军指挥官之一。",
        "source_reference": "《远东国际军事法庭判决书》；南京事件史料集",
    },
    "curated-person-tani-hisao": {
        "id": "curated-person-tani-hisao",
        "name_raw": "谷寿夫",
        "canonical_name_zh_cn": "谷寿夫",
        "traditional_name": "谷壽夫",
        "birth_year": 1882,
        "death_year": 1947,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["谷寿夫"],
        "intro_zh_cn": "日本陆军第二军第六师团长。南京战事相关审判中被判处死刑。",
        "source_reference": "南京军事法庭判决书（1947）；南京事件史料",
    },
    "curated-person-mutaguchi-renya": {
        "id": "curated-person-mutaguchi-renya",
        "name_raw": "牟田口廉也",
        "canonical_name_zh_cn": "牟田口廉也",
        "traditional_name": "牟田口廉也",
        "birth_year": 1888,
        "death_year": 1966,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["牟田口"],
        "intro_zh_cn": "日本陆军军官，卢沟桥事变时的联队长。",
        "source_reference": "《牟田口廉也回忆录》；侵华日军驻屯军史料",
    },
    "curated-person-hirohito": {
        "id": "curated-person-hirohito",
        "name_raw": "裕仁",
        "canonical_name_zh_cn": "裕仁",
        "traditional_name": "裕仁",
        "birth_year": 1901,
        "death_year": 1989,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic", "period-modern"],
        "aliases": ["昭和天皇"],
        "intro_zh_cn": "日本第124代天皇（昭和天皇），在位期间经历第二次世界大战。",
        "source_reference": "《昭和天皇实录》（宫内厅）；NHK资料",
    },
}