# -*- coding: utf-8 -*-
"""V2.1.1 · 补充 Person 规格 · 批次C：民国 / 抗日战争（中国方面）"""

from __future__ import annotations

from typing import Any

PERSON_SPECS: dict[str, dict[str, Any]] = {
    "curated-person-zhang-xueliang": {
        "id": "curated-person-zhang-xueliang",
        "name_raw": "张学良",
        "canonical_name_zh_cn": "张学良",
        "traditional_name": "張學良",
        "birth_year": 1901,
        "death_year": 2001,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic", "period-modern"],
        "aliases": ["汉卿"],
        "intro_zh_cn": "民国东北军将领，西安事变发动者（与杨虎城共同）。",
        "source_reference": "《张学良口述历史》；西安事变专题史料集",
    },
    "curated-person-chiang-kai-shek": {
        "id": "curated-person-chiang-kai-shek",
        "name_raw": "蒋介石",
        "canonical_name_zh_cn": "蒋介石",
        "traditional_name": "蔣介石",
        "birth_year": 1887,
        "death_year": 1975,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic", "period-modern"],
        "aliases": ["蒋中正", "中正"],
        "intro_zh_cn": "民国时期军事政治人物，抗战期间任国防最高委员会主席、盟军中国战区最高统帅。",
        "source_reference": "《蒋介石日记》；黄仁宇《从大历史的角度读蒋介石日记》",
    },
    "curated-person-yang-hucheng": {
        "id": "curated-person-yang-hucheng",
        "name_raw": "杨虎城",
        "canonical_name_zh_cn": "杨虎城",
        "traditional_name": "楊虎城",
        "birth_year": 1893,
        "death_year": 1949,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["虎臣"],
        "intro_zh_cn": "民国第十七路军将领，与张学良发动西安事变。",
        "source_reference": "《杨虎城将军传》——陕西人民出版社",
    },
    "curated-person-zhou-enlai": {
        "id": "curated-person-zhou-enlai",
        "name_raw": "周恩来",
        "canonical_name_zh_cn": "周恩来",
        "traditional_name": "周恩來",
        "birth_year": 1898,
        "death_year": 1976,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic", "period-modern"],
        "aliases": ["翔宇"],
        "intro_zh_cn": "现代中国政治家，中华人民共和国首任国务院总理。",
        "source_reference": "《周恩来年谱》中央文献出版社",
    },
    "curated-person-mao-zedong": {
        "id": "curated-person-mao-zedong",
        "name_raw": "毛泽东",
        "canonical_name_zh_cn": "毛泽东",
        "traditional_name": "毛澤東",
        "birth_year": 1893,
        "death_year": 1976,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic", "period-modern"],
        "aliases": ["润之"],
        "intro_zh_cn": "现代中国政治人物，中华人民共和国开国领导人。",
        "source_reference": "《毛泽东年谱》中央文献出版社",
    },
    "curated-person-song-zheyuan": {
        "id": "curated-person-song-zheyuan",
        "name_raw": "宋哲元",
        "canonical_name_zh_cn": "宋哲元",
        "traditional_name": "宋哲元",
        "birth_year": 1885,
        "death_year": 1940,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["明轩"],
        "intro_zh_cn": "民国第二十九军军长，七七事变时驻防华北的高级将领。",
        "source_reference": "《二十九军史》；《中国抗日战争全史》",
    },
    "curated-person-qin-dechun": {
        "id": "curated-person-qin-dechun",
        "name_raw": "秦德纯",
        "canonical_name_zh_cn": "秦德纯",
        "traditional_name": "秦德純",
        "birth_year": 1893,
        "death_year": 1963,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["绍文"],
        "intro_zh_cn": "民国时期第二十九军高级将领、北平市长，七七事变时期的华北军政主持人。",
        "source_reference": "《秦德纯回忆录》；《中国抗日战争全史》",
    },
    "curated-person-tang-shengzhi": {
        "id": "curated-person-tang-shengzhi",
        "name_raw": "唐生智",
        "canonical_name_zh_cn": "唐生智",
        "traditional_name": "唐生智",
        "birth_year": 1889,
        "death_year": 1970,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["孟潇"],
        "intro_zh_cn": "民国军人，南京保卫战守军总指挥。",
        "source_reference": "《唐生智》湖南人民出版社；南京保卫战史料",
    },
}