# -*- coding: utf-8 -*-
"""V2.1.1 · 补充 Person 规格 · 批次B：近代中国（清代末期 / 民国 / 抗战）"""

from __future__ import annotations

from typing import Any

PERSON_SPECS: dict[str, dict[str, Any]] = {
    "curated-person-songhuizong": {
        "id": "curated-person-songhuizong",
        "name_raw": "宋徽宗",
        "canonical_name_zh_cn": "赵佶(宋徽宗)",
        "traditional_name": "趙佶(宋徽宗)",
        "birth_year": 1082,
        "death_year": 1135,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-northern-song"],
        "aliases": ["宋徽宗", "赵佶", "道君皇帝"],
        "intro_zh_cn": "北宋末代皇帝，靖康之变中被俘北去。",
        "source_reference": "《宋史·徽宗本纪》；《续资治通鉴长编》",
    },
    "curated-person-cixi-taihou": {
        "id": "curated-person-cixi-taihou",
        "name_raw": "慈禧太后",
        "canonical_name_zh_cn": "慈禧太后",
        "traditional_name": "慈禧太后",
        "birth_year": 1835,
        "death_year": 1908,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "female",
        "period_ids": ["period-late-qing"],
        "aliases": ["叶赫那拉氏", "西太后", "老佛爷"],
        "intro_zh_cn": "晚清太后，同治、光绪两朝实际掌权者；甲午战争期间主政。",
        "source_reference": "《清史稿·后妃传》；《清德宗实录》",
    },
    "curated-person-sun-yat-sen": {
        "id": "curated-person-sun-yat-sen",
        "name_raw": "孙中山",
        "canonical_name_zh_cn": "孙中山",
        "traditional_name": "孫中山",
        "birth_year": 1866,
        "death_year": 1925,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["孙文", "孙逸仙", "中山", "逸仙"],
        "intro_zh_cn": "近代革命运动领导人，曾任中华民国临时大总统。",
        "source_reference": "《孙中山全集》；张岂之主编《中国历史·晚清卷》",
    },
    "curated-person-longyu": {
        "id": "curated-person-longyu",
        "name_raw": "隆裕太后",
        "canonical_name_zh_cn": "隆裕太后",
        "traditional_name": "隆裕太后",
        "birth_year": 1868,
        "death_year": 1913,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "female",
        "period_ids": ["period-late-qing"],
        "aliases": ["隆裕皇后", "光绪皇后"],
        "intro_zh_cn": "清光绪帝皇后，宣统继位后为隆裕太后，下诏退位。",
        "source_reference": "《清史稿·后妃传》；《宣统政草本纪》",
    },
    "curated-person-chen-duxiu": {
        "id": "curated-person-chen-duxiu",
        "name_raw": "陈独秀",
        "canonical_name_zh_cn": "陈独秀",
        "traditional_name": "陳獨秀",
        "birth_year": 1879,
        "death_year": 1942,
        "birth_precision": "year",
        "death_precision": "year",
        "gender": "male",
        "period_ids": ["period-republic"],
        "aliases": ["仲甫", "实庵"],
        "intro_zh_cn": "新文化运动主要人物，创办《青年杂志》（《新青年》）。",
        "source_reference": "《陈独秀文集》人民出版社；《新青年》",
    },
}